<div class="container mt-2" style="background-color: white;
    height: auto;
    min-height: 80vh;
    max-height: calc(100vh - 62px); overflow: hidden; 
     ">

    <form action="<?= URL_MAIN . URL_ROOT ?>/medewerkers/zoeken" method="post">
        <div class="input-group pt-2">
            <input type="search" class="form-control rounded" placeholder="Zoek op e-mailadres" aria-label="Search" aria-describedby="search-addon" name="searchField" value="<?= $email ?? '' ?>" />
            <button type="submit" class="btn btn-outline-primary">search</button>
        </div>
    </form>

    <p class="text-center w-100">
        <?php echo (is_null($employees) ? "Geen gebruikers gevonden." : sprintf("%s resultaten gevonden", count($employees)))  ?>
    </p>
    <div style="max-height: 100vh;
overflow: auto;">
        <?php
        if (!is_null($employees)) :
            foreach ($employees as $employee) {
        ?>
                <div class="row">
                    <div class="card p-0 mb-1">
                        <div class="card-body">
                            <?php
                            echo '<h5>#' . $employee['auth_id']  . ' ' . $employee["first_name"] . ' ' . $employee['infix'] . ' ' . $employee['last_name'] . '</h5>';
                            echo "<p class='m-0'>" . $employee['email'] . '</p>';
                            ?>
                        </div>
                        <div class="card-footer">

                            <?php if ($employee['employee'] === 1) { ?>
                                <form method="POST" action="<?= URL_MAIN . URL_ROOT ?>/medewerkers">
                                    <input hidden type="text" name="id" value="<?= $employee['auth_id'] ?>">
                                    <input hidden type="text" name="employee" value="0">
                                    <button type='submit' class='btn btn-danger'>Medewerker inactief stellen</button>
                                </form>
                            <?php } else { ?>
                                <form method="POST" action="<?= URL_MAIN . URL_ROOT ?>/medewerkers">
                                    <input hidden type="text" name="id" value="<?= $employee['auth_id'] ?>">
                                    <input hidden type="text" name="employee" value="1">
                                    <button type='submit' class='btn btn-success'>Medewerker maken</button>
                                </form>
                            <?php } ?>
                        </div>
                    </div>
                </div>
        <?php
            }
        endif;
        ?>
    </div>
</div>