<!--THIS IS THE CONVERTIONRATIO-->
<div class="card text-center">
    <div class="card-header">
    </div>
    <div class="card-body">
        <h5 class="card-title">Convertion ratio</h5>
        <p class="card-text"><?php echo ($ratio[0]["ratio"])?>%</p>
    </div>
    <div class="card-footer text-muted">
        Last updated: <?php echo ($ratio[0]["update_date"])?>
    </div>
</div>

<!--THIS IS THE TOTAL USER COUNT-->
<div class="card text-center">
    <div class="card-header">
    </div>
    <div class="card-body">
        <h5 class="card-title">Total registered users</h5>
        <p class="card-text"><?php echo ($registered_users)["user_count"]?></p>
    </div>
    <div class="card-footer text-muted">
        Last updated: <?php echo ($registered_users["latest_created_at"])?>
    </div>
</div>

<!--THIS IS THE TOTAL ORDER COUNT-->
<div class="card text-center">
    <div class="card-header">
    </div>
    <div class="card-body">
        <h5 class="card-title">Total oder count</h5>
        <p class="card-text"><?php echo ($total_orders)["order_count"]?></p>
    </div>
    <div class="card-footer text-muted">
        Last updated: <?php echo ($total_orders["last_order"])?>
    </div>
</div>