<style>
	.card-img-top {
		height: 300px;
		width: 300px;
		object-fit: contain;
	}
</style>

<div class="container">
	<div class="row justify-content-center text-center">
		<div class="col-md-8 col-lg-6 mb-4">
			<div class="header">
				<h1 class="text-center"><?= SITE_NAME ?></h1>
				<form class="actions__search-product input-group" action="" method="get">
					<input id="search-field" value="<?= $_GET["search"] ?? '' ?>" class="actions__search-product-input form-control" type="text" name="search" placeholder="Zoeken" aria-label="search">
					<button class="btn btn-success" type="submit">
						<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
							<path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
						</svg>
					</button>
				</form>

			</div>
		</div>
	</div>
	<div class="row">
		<div class="<?= count($products) > 0 ? "d-none" : "text-center" ?>">
			Geen producten gevonden.
		</div>

		<?php
		foreach ($products as $product) {
		?>
			<div class="col-3 mb-4">
				<a href="./product?product_id=<?= $product['id'] ?>">
					<div class="card shadow">
						<img src="<?= $product['img_path'] ?? 'https://placehold.co/300x300?text=placeholder' ?>" class="card-img-top" alt="">
						<div class="card-body">
							<h5 class="card-title"><?= $product['product_name'] ?> </h5>
						</div>
					</div>
				</a>
			</div>
		<?php
		}
		?>
	</div>
</div>