<div class="modal fade" id="shoppingCart" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="shoppingCartLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="shoppingCartLabel">Winkelmandje</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Foto</th>
                            <th>Info</th>
                            <th class="text-center">Aantal</th>
                            <th class="text-end">Prijs</th>
                        </tr>
                    </thead>
                    <tbody id="shopping-cart-body"></tbody>
                    <tfoot>
                        <tr>
                            <th colspan="3" class="text-end">Totaal:</th>
                            <th id="shopping-cart-total-price" class="text-end"></th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <div class="modal-footer">
                <a href="<?= URL_ROOT ?>/checkout" class="btn btn-success">Afrekenen</a>
            </div>
        </div>
    </div>
</div>