<style>
    .container-iframe {
        position: relative;
        overflow: hidden;
        width: 100%;
        padding-top: 56.25%;
        /* 16:9 Aspect Ratio (divide 9 by 16 = 0.5625) */
    }

    .responsive-iframe {
        position: absolute;
        top: 0;
        left: 0;
        bottom: 0;
        right: 0;
        width: 100%;
        height: 100%;
    }
</style>
<div class="container-lg mt-5">
    <div class="row h-100">
        <div class="row mb-4">
            <div class="col-md-6">
                <div class="card shadow h-100 p-4">
                    <div id="productCarousel" class="carousel" data-bs-ride="carousel">
                        <div class="carousel-inner slide">
                            <div class="carousel-item h-100 text-center active">
                                <img src="<?= $product['img_path'] ?? 'https://placehold.co/500x500?text=Geen%20product%20foto' ?>" class="h-100" alt="Product foto">
                            </div>
                            <div class="carousel-item h-100 text-center">
                                <div class="container-iframe">
                                    <!-- <iframe class="responsive-iframe" type="text/html" src="<?= $product['video_url'] ?? 'https://www.youtube.com/embed/dQw4w9WgXcQ' ?>" frameborder="0" allowfullscreen>
                                    </iframe> -->

                                </div>
                            </div>
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#productCarousel" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#productCarousel" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card shadow h-100">
                    <div class="card-header">
                        <h2>
                            <?= $product['product_name'] ?>
                        </h2>
                    </div>
                    <div class="card-body d-flex align-items-start flex-column h-100">
                        <div class="mb-auto p-2">
                            <p>
                                <b>Merk:</b> <?= $product['brand_name'] ?>
                            </p>
                            <p>
                                <b>Beschrijving:</b>
                                <br>
                                <?= $product['description'] ?>
                            </p>
                            <?php if (count($productCategories) > 0) { ?>
                                <p>
                                    <b>Catagorien:</b>
                                <ul>
                                    <?php foreach ($productCategories as $category) { ?>
                                        <li> <?= $category['category_name'] ?></li>
                                    <?php } ?>
                                </ul>
                                </p>
                            <?php } ?>
                        </div>

                        <div class="p-2">
                            <div>
                                <b>Prijs:</b> &euro; <?= number_format($product['price'], 2, ',', '.') ?>
                            </div>
                            <div>
                                <?php if ($product['quantity'] > 5) { ?>
                                    <div><b>Voorraad:</b> <?= $product['quantity'] ?> stuks</div>
                                <?php } ?>
                                <?php if ($product['quantity'] > 1 && $product['quantity'] <= 5) { ?>
                                    <div><b class="text-warning">Let op!</b> Er zijn nog maar <?= $product['quantity'] ?> stuks beschikbaar!</div>
                                <?php } ?>
                                <?php if ($product['quantity'] == 1) { ?>
                                    <div><b class="text-warning">Let op!</b> Er is nog maar <?= $product['quantity'] ?> beschikbaar!</div>
                                <?php } ?>
                                <?php if ($product['quantity'] === 0) { ?>
                                    <div class="text-danger">Product is helaas niet leverbaar.</div>
                                <?php } ?>
                            </div>
                        </div>
                        <div class="p-2">
                            <div class="row mb-2">
                                <div class="col-4">
                                    <div class="input-group">
                                        <span role="button" class="input-group-text" onclick="inputMinus(this)">-</span>
                                        <input id="product-amount" type="number" class="form-control text-center" value="1" required>
                                        <span role="button" class="input-group-text" onclick="inputAdd(this)">+</span>
                                    </div>
                                </div>
                                <div class="col">
                                    <?php if ($product['quantity'] === 0) { ?>
                                        <button class="btn btn-outline-secondary" disabled>In winkelwagen</button>
                                    <?php } else { ?>
                                        <button class="btn btn-success" id="cart-button" type="button" onclick="addToCart()">In winkelwagen</button>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function addToCart() {
        const id = <?= $product['id'] ?>;
        const amount = parseInt($('#product-amount').val());
        addToShoppingCart(id, amount, <?= $product['price'] ?>, "<?= $product['product_name'] ?>", "<?= $product['img_path'] ?? 'https://placehold.co/50x50?text=Geen%20product%20foto' ?>");
    }
</script>