<?php

if (!empty($_POST)) {
  $error = login_account();
}
?>
<img src="./public/img/stock_foto_guitars.jpeg" alt="" style=" position: absolute;  height: 100%; width: 100%; background-position: center; background-repeat: no-repeat; background-size: cover;">
</img>
<section class="h-100 h-custom">
  <div class="container py-5 h-100">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
      <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-9 col-lg-7 mt-5 col-xl-6 h-100">
            <div class="card" style="border-radius: 15px;">
              <div class="card-body p-5">
                <h2 class="text-uppercase text-center mb-5">Login met een bestaand account</h2>

                <form action="" id="login_form" method="post">
                  <div class="form-outline form-white mb-4">
                    <label class="form-label required  <?= empty($error["email"]) ? "" : "invalid-feedback" ?> " style="display: block !important;" for="form_email">
                      <?= empty($error["email"]) ? "Emailadres" : $error["email"] ?>
                    </label>
                    <input type="text" name="form_email" id="form_email" class="form-control  form-control-lg <?= empty($error["email"]) ? "" : "is-invalid" ?>" />

                  </div>

                  <div class="form-outline mb-4 ">
                    <label class="form-label" for="form_password">Wachtwoord</label>
                    <div class="d-flex justify-content-between ">
                      <input type="password" id="form_password" class="form-control form-control-lg" name="form_password" required />
                      <em class="far fa-eye d-flex  justify-content-center align-self-center rounded-right" id="togglePassword" style=" line-height: 0;margin-left: -50px; cursor: pointer; background-color: gray; width:50px;"></em>
                    </div>
                  </div>
                  <div class="d-flex justify-content-center">
                    <button type="button" id="submit-btn-login" class="btn btn-success btn-block btn-lg">Inloggen</button>
                  </div>

                  <p class="text-center text-muted mt-5 mb-0">Heeft u nog geen account?<br> Klik dan hier om te <a href="./register" class="fw-bold text-body"> <u>Registreren</u></a></p>

                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<script src="./public/js/login.js"></script>