<?php /** @var $user */ ?>

<script type="text/javascript" src="./public/js/checkout.js"></script>

<div id="checkout-container" class="checkout-container container">
    <div class="row gx-4">

        <!-- Payment details -->
        <div class="col-8">
            <div class="payment-details-container rounded border bg-white shadow px-5 py-4">
                <h3 class="text-center">Bestel gegevens</h3>
                <form id="payment-details-form" action="./confirm-payment" method="post">

                    <!-- Contact details -->
                    <h5 class="mt-3">Contactgegevens</h5>
                    <div class="row g-4">
                        <div class="col-4">
                            <div class="form-floating mb-4 ">
                                <input id="first-name-input" class="input form-control" type="text" placeholder="Voornaam" value="<?= $user['firstName'] ?? '' ?>" name="firstName">
                                <label id="first-name-label" for="first-name-input" class="text-secondary">Voornaam <span class="text-danger">*</span></label>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-floating mb-4">
                                <input id="infix-input" class="input form-control" type="text" placeholder="Tussenvoegsel" value="<?= $user['infix'] ?? '' ?>" name="infix">
                                <label id="infix-label" for="infix-input" class="text-secondary">Tussenvoegsel</label>
                            </div>
                        </div>
                        <div class="col-5">
                            <div class="form-floating mb-4">
                                <input id="last-name-input" class="input form-control" type="text" placeholder="Achternaam" value="<?= $user['lastName'] ?? '' ?>" name="lastName">
                                <label id="last-name-label" for="last-name-input" class="text-secondary">Achternaam <span class="text-danger">*</span></label>
                            </div>
                        </div>
                    </div>
                    <div class="row g-4">
                        <div class="col-7">
                            <div class="form-floating mb-4">
                                <input id="email-input" class="input form-control" type="email" placeholder="E-mailadres" value="<?= $user['email'] ?? '' ?>" name="email">
                                <label id="email-label" for="mail-input" class="text-secondary">E-mailadres <span class="text-danger">*</span></label>
                            </div>
                        </div>
                        <div class="col-5">
                            <div class="form-floating mb-4">
                                <input id="phone-number-input" class="input form-control" type="number" placeholder="Telefoonnummer" value="<?= $user['phoneNumber'] ?? '' ?>" name="phoneNumber">
                                <label id="phone-number-label" for="phone-number-input" class="text-secondary">Telefoonnummer</label>
                            </div>
                        </div>
                    </div>

                    <!-- Address details -->
                    <h5 class="mt-3">Adresgegevens</h5>
                    <div class="row g-3">
                        <div class="col-2">
                            <div class="form-floating mb-3">
                                <input id="zip-code-input" class="input form-control" type="text" placeholder="Postcode" value="<?= $user['zipCode'] ?? '' ?>" name="zipCode">
                                <label for="zip-code-input" class="text-secondary">Postcode <span class="text-danger">*</span></label>
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="form-floating mb-3">
                                <input id="street-name-input" class="input form-control" type="text" placeholder="Straatnaam" value="<?= $user['streetName'] ?? '' ?>" name="streetName">
                                <label for="street-name-input" class="text-secondary">Straatnaam <span class="text-danger">*</span></label>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="form-floating mb-3">
                                <input id="house-number-input" class="input form-control" type="text" placeholder="Nummer" value="<?= $user['houseNumber'] ?? '' ?>" name="houseNumber">
                                <label for="house-number-input" class="text-secondary">Nummer <span class="text-danger">*</span></label>
                            </div>
                        </div>
                    </div>
                    <div class="row g-3">
                        <div class="col-5">
                            <div class="form-floating mb-3">
                                <input id="city-input" class="input form-control" type="text" placeholder="Stad" value="<?= $user['city'] ?? '' ?>" name="city">
                                <label for="city-input" class="text-secondary">Stad <span class="text-danger">*</span></label>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-floating mb-3">
                                <select id="country-input" class="input form-select form-control" name="country">
                                    <?php
                                    echo empty($user['country']) ? "<option disabled selected>Kies een land</option>" : "<option disabled>Kies een land</option>";

                                    $countries = ['Nederland','België','Luxemburg'];
                                    foreach ($countries as $country) {
                                        echo $user['country'] === $country ? "<option selected value='$country'>$country</option>" : "<option value='$country'>$country</option>";
                                    }
                                    ?>
                                </select>
                                <label for="country-input" class="text-secondary">Land <span class="text-danger">*</span></label>
                            </div>
                        </div>
                    </div>

                    <!-- Payment details -->
                    <h5 class="mt-3">Betaalgegevens</h5>
                    <div class="row g-3">
                        <div class="col-3">
                            <div class="form-floating mb-3">
                                <select id="bank-name-input" class="input form-select form-control" onchange="preFillBankAccountCodes(event)" name="bankName">
                                    <option disabled selected>Kies een bank</option>
                                    <option value="ABN-Amro">ABN-Amro</option>
                                    <option value="ASN Bank">ASN Bank</option>$request['bankAccount']
                                    <option value="Bunq">Bunq</option>
                                    <option value="ING">ING</option>
                                    <option value="Knab">Knab</option>
                                    <option value="Rabobank">Rabobank</option>
                                    <option value="SNS Bank">SNS Bank</option>
                                </select>
                                <label for="bank-name-input" class="text-secondary">Bank <span class="text-danger">*</span></label>
                            </div>
                        </div>
                        <div class="col-9">
                            <label for="bank-account-input" class="text-secondary">Rekeningnummer <span class="text-danger">*</span></label>
                            <div id="bank-account-input" class="d-flex mb-3">
                                <input id="bank-account-input-1" class="bank-account-input input form-control p-1 me-1 text-center" type="text" maxlength="1" oninput="nextBankAccountInputField(event)" name="bankAccount1">
                                <input id="bank-account-input-2" class="bank-account-input input form-control p-1 me-1 text-center" type="text" maxlength="1" oninput="nextBankAccountInputField(event)" name="bankAccount2">
                                <input id="bank-account-input-3" class="bank-account-input input form-control p-1 me-1 text-center" type="number" oninput="nextBankAccountInputField(event)" onKeyPress="if(this.value.length === 1) return false;" name="bankAccount3">
                                <input id="bank-account-input-4" class="bank-account-input input form-control p-1 me-3 text-center" type="number" oninput="nextBankAccountInputField(event)" onKeyPress="if(this.value.length === 1) return false;" name="bankAccount4">
                                <input id="bank-account-input-5" class="bank-account-input input form-control p-1 me-1 text-center" type="text" maxlength="1" oninput="nextBankAccountInputField(event)" name="bankAccount5">
                                <input id="bank-account-input-6" class="bank-account-input input form-control p-1 me-1 text-center" type="text" maxlength="1" oninput="nextBankAccountInputField(event)" name="bankAccount6">
                                <input id="bank-account-input-7" class="bank-account-input input form-control p-1 me-1 text-center" type="text" maxlength="1" oninput="nextBankAccountInputField(event)" name="bankAccount7">
                                <input id="bank-account-input-8" class="bank-account-input input form-control p-1 me-3 text-center" type="text" maxlength="1" oninput="nextBankAccountInputField(event)" name="bankAccount8">
                                <input id="bank-account-input-9" class="bank-account-input input form-control p-1 me-1 text-center" type="number" oninput="nextBankAccountInputField(event)" onKeyPress="if(this.value.length === 1) return false;" name="bankAccount9">
                                <input id="bank-account-input-10" class="bank-account-input input form-control p-1 me-1 text-center" type="number" oninput="nextBankAccountInputField(event)" onKeyPress="if(this.value.length === 1) return false;" name="bankAccount10">
                                <input id="bank-account-input-11" class="bank-account-input input form-control p-1 me-1 text-center" type="number" oninput="nextBankAccountInputField(event)" onKeyPress="if(this.value.length === 1) return false;" name="bankAccount11">
                                <input id="bank-account-input-12" class="bank-account-input input form-control p-1 me-3 text-center" type="number" oninput="nextBankAccountInputField(event)" onKeyPress="if(this.value.length === 1) return false;" name="bankAccount12">
                                <input id="bank-account-input-13" class="bank-account-input input form-control p-1 me-1 text-center" type="number" oninput="nextBankAccountInputField(event)" onKeyPress="if(this.value.length === 1) return false;" name="bankAccount13">
                                <input id="bank-account-input-14" class="bank-account-input input form-control p-1 me-1 text-center" type="number" oninput="nextBankAccountInputField(event)" onKeyPress="if(this.value.length === 1) return false;" name="bankAccount14">
                                <input id="bank-account-input-15" class="bank-account-input input form-control p-1 me-1 text-center" type="number" oninput="nextBankAccountInputField(event)" onKeyPress="if(this.value.length === 1) return false;" name="bankAccount15">
                                <input id="bank-account-input-16" class="bank-account-input input form-control p-1 me-3 text-center" type="number" oninput="nextBankAccountInputField(event)" onKeyPress="if(this.value.length === 1) return false;" name="bankAccount16">
                                <input id="bank-account-input-17" class="bank-account-input input form-control p-1 me-1 text-center" type="number" oninput="nextBankAccountInputField(event)" onKeyPress="if(this.value.length === 1) return false;" name="bankAccount17">
                                <input id="bank-account-input-18" class="bank-account-input input form-control p-1 me-1 text-center" type="number" onKeyPress="if(this.value.length==1) return false;" name="bankAccount18">
                            </div>
                        </div>
                    </div>

                    <!-- Products -->
                    <input id="products-input" class="d-none" name="products">
                    <input id="total-price-input" class="d-none" name="totalPrice">

                    <div class=" d-flex justify-content-between mt-2">
                        <span class="text-danger">* Verplicht</span>
                        <span id="error-message" class="d-none text-danger">Sommige velden zijn niet goed ingevuld!</span>
                    </div>
                    <button class="btn btn-success mt-2 w-100" type="button" onclick="validateForm()">Bestelling bevestigen</button>
                </form>
            </div>
        </div>

        <!-- Order overview -->
        <div class="col-4">
            <div class="order-overview-container rounded border-success bg-success shadow p-3 overflow-hidden">
                <h3 class="text-center text-white mb-3">Uw bestelling</h3>

                <!-- Product list -->
                <div class="rounded overflow-hidden">
                    <div class="row bg-light p-3 border-bottom ">
                        <div class="col-6 d-flex align-items-center"><h5 class="m-0">Product</h5></div>
                        <div class="col-3 text-center"><h5 class="m-0">Prijs</h5><h6 class="m-0">(per stuk)</h6></div>
                        <div class="col-3 d-flex align-items-center text-center"><h5 class="m-0">Aantal</h5></div>
                    </div>
                    <div id="product-list-body" class="product-list-body bg-white">
                    <!-- Generated by javascript -->
                    </div>
                    <div class="product-list-footer d-flex justify-content-between text-black border-top p-3">
                        <h5 class="m-0">Totaalprijs:</h5>
                        <h5 id="total-price" class="m-0"></h5>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
